CXX = g++
CXXFLAGS = -Wall -Werror -Wextra -pedantic -std=c++17 -g -fsanitize=address
LDFLAGS =  -fsanitize=address

SRC = rain.cpp Weia2.cpp
OBJ = $(SRC:.cc=.o)
EXEC = RainFallStats

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $(OBJ) $(LBLIBS)

run: 
	./$(EXEC)

clean:
	rm -rf $(OBJ) $(EXEC)